### ISSUE TITLE
请教下getdefaultgateway6()函数是如何实现

### ISSUE THREAD

**Issue by vintonliu** [WeMobileDev/article#4]

**Comment by wangyoucao577** [comment]
源码在`getgateway.c`中, 仅在宏`USE_SYSCTL_NET_ROUTE`中实现了一份`getdefaeultgateway6`. 此宏在`Linux`, `BSD`, `Windows`上并未定义, `Apple(ios, mac)`上有定义.   

故可认为仅在`Apple`平台上支持了此功能, 为了通过Appstore的审核...

注: 参考代码 Mars(https://github.com/Tencent/mars)

**Comment by wenchang85** [comment]
@wangyoucao577 已经在网上找了相关资料，实现了。
