### ISSUE TITLE
关于热修复art插桩会导致寻址错误

### ISSUE THREAD

**Issue by dustookk** [WeMobileDev/article#6]
首先感谢微信团队的付出.   关于热修复一文中提到的art插桩会导致寻址错误的问题, 文中解释的不是很清楚, 我用手Q的热修复方法测试了art多个机型, 修改方法名修改变量名都正常修复并且没有引起其它问题.  

![abc](https://cloud.githubusercontent.com/assets/1394913/18236406/19d81dce-7358-11e6-8ad8-774461679881.png)

**Comment by shwenzhang** [comment]
事实上，很多时候修改也不会导致一定出问题，而且出问题有时候表现也不一定是crash

**Comment by dustookk** [comment]
感谢回复 : )
